src/api/config/routes.rb
# we take everything here that is not XML - the default mimetype is xml though
class WebuiMatcher
  class InvalidRequestFormat < APIException
  end

  def self.matches?(request)
    request.format.to_sym != :xml
  rescue ArgumentError => e
    raise InvalidRequestFormat, e.to_s
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    format == :xml || format == :json || public_or_about_path?(request)
  end

  def self.public_or_about_path?(request)
    request.fullpath.start_with?('/public', '/about')
  end
end

OBSApi::Application.routes.draw do
  mount Peek::Railtie => '/peek'

  cons = {
    arch:         %r{[^\/]*},
    binary:       %r{[^\/]*},
    filename:     %r{[^\/]*},
    id:           %r{\d*},
    login:        %r{[^\/]*},
    package:      %r{[^\/]*},
    package_name: %r{[^\/]*},
    project:      %r{[^\/]*},
    project_name: %r{[^\/]*},
    repository:   %r{[^\/]*},
    service:      %r{\w[^\/]*},
    title:        %r{[^\/]*},
    user:         %r{[^\/]*}
  }

  constraints(WebuiMatcher) do
    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
    end

    resources :status_messages, only: [:create, :destroy], controller: 'webui/status_messages' do
      collection do
        get 'create_status_message_dialog' => :create_status_message_dialog
        get 'destroy_status_message_dialog' => :destroy_status_message_dialog
      end
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, constraints: ->(req) { req.format == :rss }, as: :news_feed
      get 'main/latest_updates' => :latest_updates, constraints: ->(req) { req.format == :rss }, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
      get 'user/feed/:token' => :notifications, defaults: { format: 'rss' }, as: :user_rss_notifications
    end

    resources :attribs, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/attribute' do
      collection do
        get ':project(/:package)/new' => :new, constraints: cons, as: 'new'
        get ':project(/:package)/:attribute/edit' => :edit, constraints: cons, as: 'edit'
        get ':project(/:package)' => :index, constraints: cons, as: 'index', defaults: { format: 'html' }
      end
    end

    resources :image_templates, constraints: cons, only: [:index], controller: 'webui/image_templates'

    resources :download_repositories, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/download_on_demand'

    controller 'webui/configuration' do
      get 'configuration' => :index
      patch 'configuration' => :update
      get 'configuration/interconnect' => :interconnect
      post 'configuration/interconnect' => :create_interconnect
    end

    controller 'webui/subscriptions' do
      get 'notifications' => :index
      put 'notifications' => :update
    end

    controller 'webui/architectures' do
      get 'architectures' => :index
      patch 'architectures/bulk_update_availability' => :bulk_update_availability, as: 'bulk_update_availability'
    end

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events, as: :monitor_events
    end

    defaults format: 'html' do
      controller 'webui/package' do
        get 'package/show/:project/:package' => :show, as: 'package_show', constraints: cons
        get 'package/dependency/:project/:package' => :dependency, constraints: cons
        get 'package/binary/:project/:package/:repository/:arch/:filename' => :binary, constraints: cons, as: 'package_binary'
        get 'package/binaries/:project/:package/:repository' => :binaries, constraints: cons, as: 'package_binaries'
        get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
        get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
        get 'package/statistics/:project/:package/:repository/:arch' => :statistics, as: 'package_statistics', constraints: cons
        get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
        post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
        get 'package/add_person/:project/:package' => :add_person, constraints: cons
        get 'package/add_group/:project/:package' => :add_group, constraints: cons
        get 'package/rdiff/:project/:package' => :rdiff, constraints: cons, as: 'package_rdiff'
        post 'package/save_new/:project' => :save_new, constraints: cons
        post 'package/branch' => :branch, constraints: cons
        post 'package/save/:project/:package' => :save, constraints: cons
        post 'package/remove/:project/:package' => :remove, constraints: cons
        get 'package/add_file/:project/:package' => :add_file, constraints: cons
        post 'package/save_file/:project/:package' => :save_file, constraints: cons
        post 'package/remove_file/:project/:package/:filename' => :remove_file, constraints: cons
        post 'package/save_person/:project/:package' => :save_person, constraints: cons
        post 'package/save_group/:project/:package' => :save_group, constraints: cons
        post 'package/remove_role/:project/:package' => :remove_role, constraints: cons
        get 'package/view_file/:project/:package/(:filename)' => :view_file, constraints: cons, as: 'package_view_file'
        get 'package/live_build_log/:project/:package/:repository/:arch' => :live_build_log, constraints: cons, as: 'package_live_build_log'
        defaults format: 'js' do
          get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons
          get 'package/update_build_log/:project/:package/:repository/:arch' => :update_build_log, constraints: cons
          get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons
          get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons
          post 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons
          get 'package/abort_build/:project/:package' => :abort_build, constraints: cons
          post 'package/trigger_services/:project/:package' => :trigger_services, constraints: cons
          delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons
        end
        get 'package/devel_project/:project/:package' => :devel_project, constraints: cons
        get 'package/buildresult' => :buildresult, constraints: cons
        get 'package/rpmlint_result' => :rpmlint_result, constraints: cons
        get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
        get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
        post 'package/save_meta/:project/:package' => :save_meta, constraints: cons
        # compat route
        get 'package/attributes/:project/:package', to: redirect('/attribs/%{project}/%{package}'), constraints: cons
        get 'package/edit/:project/:package' => :edit, constraints: cons, as: :package_edit
        # compat routes
        get 'package/repositories/:project/:package', to: redirect('/repositories/%{project}/%{package}'), constraints: cons
        get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
        # compat route
        get 'package/files/:project/:package' => :show, constraints: cons
      end
    end

    resources :packages, only: [], param: :name do
      resource :job_history, controller: 'webui/packages/job_history', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end

      resource :build_reason, controller: 'webui/packages/build_reason', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end
    end

    controller 'webui/patchinfo' do
      post 'patchinfo/new_patchinfo' => :new_patchinfo
      post 'patchinfo/updatepatchinfo' => :updatepatchinfo
      get 'patchinfo/edit_patchinfo' => :edit_patchinfo
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show', constraints: cons, defaults: { format: 'html' }
      get 'patchinfo/read_patchinfo' => :read_patchinfo
      post 'patchinfo/save/:project/:package' => :save, constraints: cons, as: :patchinfo_save
      post 'patchinfo/remove' => :remove
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/delete_dialog' => :delete_dialog
    end
    #
    controller 'webui/repositories' do
      get 'repositories/:project(/:package)' => :index, constraints: cons, as: 'repositories', defaults: { format: 'html' }
      get 'project/repositories/:project' => :index, constraints: cons, as: 'project_repositories'
      get 'project/add_repository/:project' => :new, constraints: cons
      get 'project/add_repository_from_default_list/:project' => :distributions, constraints: cons, as: :repositories_distributions
      post 'project/save_repository' => :create
      post 'project/update_target/:project' => :update, constraints: cons
      get 'project/repository_state/:project/:repository' => :state, constraints: cons, as: 'project_repository_state'
      post 'project/remove_target' => :destroy
      post 'project/create_dod_repository' => :create_dod_repository
      post 'project/create_image_repository' => :create_image_repository

      # Flags
      put 'flag/:project(/:package)' => :toggle_flag, constraints: cons
      post 'flag/:project(/:package)' => :create_flag, constraints: cons
      delete 'flag/:project(/:package)/:flag' => :remove_flag, constraints: cons
    end

    controller 'webui/kiwi/images' do

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController
  def index
    filename = File.expand_path(CONFIG['apidocs_location']) + '/index.html'
    if File.exist?(filename)
      render file: filename, formats: [:html]
    else
      logger.error "Unable to load apidocs index file from #{CONFIG['apidocs_location']}. Did you create the apidocs?"
      flash[:error] = 'Unable to load API documentation.'
      redirect_back(fallback_location: root_path)
    end
  end

  def file
    # Ensure it really is just a file name, no '/..', etc.
    filename = File.basename(params[:filename])
    file = File.expand_path(File.join(CONFIG['schema_location'], filename))
    if File.exist?(file)
      send_file(file, type: 'text/xml', disposition: 'inline')
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back(fallback_location: { controller: 'apidocs', action: 'index' })
    end
    return
  end
end

src/api/app/controllers/webui/architectures_controller.rb
# Enabling/Disabling default architectures
class Webui::ArchitecturesController < Webui::WebuiController
  before_action :require_admin

  def index
    @architectures = Architecture.order(:name)
  end

  def bulk_update_availability
    all_valid = true
    params[:archs].each do |name, value|
      arch = Architecture.find_by(name: name)
      arch.available = value
      all_valid &&= arch.save
    end

    ::Configuration.write_to_backend

    respond_to do |format|
      if all_valid
        format.html { redirect_to architectures_path, notice: 'Architectures successfully updated.' }
      else
        format.html { redirect_back(fallback_location: root_path, error: 'Not all architectures could be saved') }
      end
    end
  end
end

src/api/app/controllers/webui/attribute_controller.rb
class Webui::AttributeController < Webui::WebuiController
  helper :all
  before_action :set_container, only: [:index, :new, :edit]
  before_action :set_attribute, only: [:update, :destroy]

  # raise an exception if authorize has not yet been called.
  after_action :verify_authorized, except: :index

  helper 'webui/project'

  def index
    @attributes = @container.attribs
  end

  def new
    if @package
      @attribute = Attrib.new(package_id: @package.id)
    else
      @attribute = Attrib.new(project_id: @project.id)
    end
    authorize @attribute, :create?
  end

  def edit
    @attribute = Attrib.find_by_container_and_fullname(@container, params[:attribute])

    authorize @attribute

    return unless @attribute.attrib_type.value_count && (@attribute.attrib_type.value_count > @attribute.values.length)
    (@attribute.attrib_type.value_count - @attribute.values.length).times { @attribute.values.build(attrib: @attribute) }
  end

  def create
    @attribute = Attrib.new(attrib_params)

    authorize @attribute

    # build the default values
    if @attribute.attrib_type.value_count
      @attribute.attrib_type.value_count.times do
        @attribute.values.build(attrib: @attribute)
      end
    end

    if @attribute.save
      if @attribute.values_editable?
        redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s,
                                      attribute: @attribute.fullname),
                    notice: 'Attribute was successfully created.'
      else
        redirect_to index_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s),
                    notice: 'Attribute was successfully created.'
      end
    else
      redirect_back(fallback_location: root_path, error: "Saving attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def update
    authorize @attribute

    if @attribute.update(attrib_params)
      redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s, attribute: @attribute.fullname),
                  notice: 'Attribute was successfully updated.'
    else
      redirect_back(fallback_location: root_path, error: "Updating attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def destroy
    authorize @attribute

    @attribute.destroy
    redirect_back(fallback_location: root_path, notice: 'Attribute sucessfully deleted!')
  end

  private

  def set_container
    begin
      @project = Project.get_by_name(params[:project])
    rescue APIException
      flash[:error] = "Project not found: #{params[:project]}"
      redirect_to(controller: 'project') && return
    end
    if params[:package]
      begin
        @package = Package.get_by_project_and_name(params[:project], params[:package], use_source: false)
      rescue APIException
        redirect_to(project_show_path(@project.to_s), error: "Package #{params[:package]} not found") && (return)
      end
      @container = @package
    else
      @container = @project
    end
  end

  def set_attribute
    @attribute = Attrib.find(params[:id])
    if @attribute.container.instance_of? Package
      @package = @attribute.container
      @project = @package.project
    elsif @attribute.container.instance_of? Project
      @project = @attribute.container
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attrib_params
    params.require(:attrib).permit(:attrib_type_id, :project_id, :package_id,
                                   values_attributes: [:id, :value, :position, :_destroy],
                                   issues_attributes: [:id, :name, :issue_tracker_id, :_destroy])
  end
end

src/api/app/controllers/webui/cloud/azure/configurations_controller.rb
module Webui
  module Cloud
    module Azure
      class ConfigurationsController < WebuiController
        before_action :require_login
        before_action :set_breadcrumb
        before_action -> { feature_active?(:cloud_upload) }
        before_action -> { feature_active?(:cloud_upload_azure) }
        before_action :set_azure_configuration

        # GET /cloud/azure/configuration
        def show
          @crumb_list << 'Azure Configuration'
        end

        # PATCH/PUT /cloud/azure/configuration
        def update
          if @azure_configuration.update(permitted_params)
            flash[:success] = 'Successfully updated your Azure configuration.'
          else
            flash[:error] = "Could not update your Azure configuration: #{@azure_configuration.errors.full_messages.to_sentence}."
          end

          redirect_to cloud_azure_configuration_path
        end

        # DELETE /cloud/azure/configuration
        def destroy
          @azure_configuration.destroy!

          flash[:success] = "You've successfully deleted your Azure configuration."
          redirect_to cloud_azure_configuration_path
        end

        private

        def set_azure_configuration
          @azure_configuration = User.current.azure_configuration || User.current.create_azure_configuration
        end

        def set_breadcrumb
          @crumb_list = [
            WebuiController.helpers.link_to('Cloud Upload', cloud_upload_index_path),
            WebuiController.helpers.link_to('Configuration', cloud_configuration_index_path)
          ]
        end

        def permitted_params
          params.require(:cloud_azure_configuration).permit(:application_id, :application_key)
        end
      end
    end
  end
end

src/api/app/controllers/webui/cloud/configurations_controller.rb
module Webui
  module Cloud
    class ConfigurationsController < WebuiController
      before_action :set_breadcrumb

      def index
        @crumb_list.push << 'Configuration'
      end

      private

      def set_breadcrumb
        @crumb_list = [WebuiController.helpers.link_to('Cloud Upload', cloud_upload_index_path)]
      end
    end
  end
end

src/api/app/views/webui/patchinfo/_delete_dialog.html.haml
.darkgrey_box.dialog#del-dialog
  .box.box-shadow
    %h2.box-header Delete Confirmation
    .dialog-content
      %p
        Do you really want to delete #{package_link @package}?
      = form_tag({ controller: :patchinfo, action: :remove}, method: :post) do
        %div
          = hidden_field_tag(:project, @project)
          = hidden_field_tag(:package, @package)
          = render partial: '/webui/shared/dialog_action_buttons'

src/api/app/views/webui/patchinfo/_form.html.haml
= render partial: 'webui/package/tabs'
= form_tag(patchinfo_save_path(project: @project, package: @package), id: 'patchinfo') do
  .section
    .grid_8.alpha
      .box.show_left.show_right
        .box{style: "background-color:#DDDDDD; margin-top: 0"}
          %h2{style: "display: inline"}
            Patchinfo-Editor for #{@project}
        .box.show_left.show_right
          %p
            %strong
              %label{for: "packager"} Packager:
            %br/
            = text_field_tag 'packager', @packager, required: true
            :javascript
              $("#packager").autocomplete({source: '#{url_for controller: 'user', action: 'autocomplete'}', search: function(event, ui) {
                $(this).addClass('loading-spinner');
              },
              response: function(event, ui) {
                $(this).removeClass('loading-spinner');
              },minLength: 2});
          %p
            %strong
              = image_tag('info.png', title: 'Enter a short summary. Mainpackage: shortdescription of the mainfix', alt: 'Summaryinfo')
              %label{for: "summary"} Summary:
            = text_area_tag 'summary', @summary, size: '60x1', required: true, min: 10
          %p
            %strong
              = image_tag('info.png', title: 'Enter a full description what the update fixes', alt: 'Descriptioninfo')
              %label{for: "description"} Description:
            = text_area_tag 'description', @description, size: '65x9', required: true, min: 10
          %p
            %strong
              = image_tag('info.png', title: 'Choose the category of your update', alt: 'Categoryinfo')
              %label{for: "category"} Category:
            = select_tag 'category', options_for_select(Patchinfo::CATEGORIES, @category)
          %p
            %strong
              = image_tag('info.png', title: 'Select the rating of this update', alt: 'Ratinginfo')
              %label{for: "rating"} Rating:
            = select_tag 'rating', options_for_select(Patchinfo::RATINGS, @rating)
        .box.show_left.show_right
          %p
            %strong
              = image_tag('info.png', title: 'List of issues what the update fixes', alt: 'Issueinfo')
              Issues:
          #issuelist
            - if @issues
              - @issues.reject { |issue| issue.blank? }.each do |issue|
                %div{id: "issue_#{issue[0]}_#{issue[1]}"}
                  = link_to image_tag('bug_delete.png', alt: 'Remove Bug', title: 'Remove Bug'), '#', onclick: "$('#issue_#{issue[0]}_#{issue[1]}').remove(); return false;", style: 'clear:both;', id: "remove_#{issue[0]}_#{issue[1]}"
                  = hidden_field_tag 'issueid[]', "#{issue[1]}", id: "issueid_#{issue[0]}_#{issue[1]}"
                  = hidden_field_tag 'issuetracker[]', "#{issue[0]}", id: "issuetracker_#{issue[0]}_#{issue[1]}"
                  = hidden_field_tag 'issueurl[]', "#{issue[2]}", id: "issueurl_#{issue[0]}_#{issue[1]}"
                  = hidden_field_tag 'issuesum[]', "#{issue[3]}", id: "issuesum_#{issue[0]}_#{issue[1]}"
                  = link_to "#{issue[0].to_s}##{issue[1].to_s}", issue[2].to_s
                  \: 
                  %div{id: "issue_desc_#{issue[0]}_#{issue[1]}", onclick: "change_issue_desc('#{issue[0]}_#{issue[1]}');"}
                    = issue[3].to_s
                  %div{id: "change_desc_#{issue[0]}_#{issue[1]}", style: "display:none;"}
                    = text_field_tag 'desc_' + issue[0] + '_' + issue[1], issue[3].to_s, size: issue[3].to_s.length
                    = link_to image_tag('ok.png', alt: 'Ok', title: 'Change description'), '#', onclick: "changeDesc('ok', '#{issue[0]}_#{issue[1]}'); return false;"
                    = link_to image_tag('req-decline.png', alt: 'Cancel', title: 'Cancel changes'), '#', onclick: "changeDesc('cancel', '#{issue[0]}_#{issue[1]}'); return false;"
          .box.show_right.show_left{style: "margin-top:5px;"}
            %p
              %label{for: "issue"}
                Add an additional bug (single or a comma-separated list e.g.: "boo#123456,
                bgo#654321,CVE-2012-1234)"
                %br/
                A list of all supported tracker you can find here:
                \#{link_to 'Tracker List', 'https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines#Current_set_of_abbreviations'}
              %input#issue{name: "issuelist", type: "text", value: "#{@issueid}"}
                = link_to image_tag('bug_add.png', alt: 'Add Bug', title: "Add additional issues e.g.: \"bnc#123456, bgo#654321\""), '#', data: { 'add-issue' => true, project: @project.name }
                = image_tag('ajax-loader.gif', id: 'issue_spinner', class: 'hidden')
          .box.show_left.show_right
            = link_to 'Update issues from sources', { action: 'updatepatchinfo', project: @project, package: @package }, { data: { confirm: 'Attention! All unsaved data will be lost! Continue?' }, method: :post }
        .box.show_left.show_right
          %p
            %strong
              = image_tag('info.png', title: 'Set the required flags for this update', alt: 'Flagsinfo')
              Required actions:
          %p
            = check_box_tag('zypp_restart_needed', true, @zypp_restart_needed)
            %label{for: "zypp_restart_needed"} Package-manager restart suggested
          %p
            = check_box_tag('relogin', true, @relogin)
            %label{for: "relogin"} Relogin suggested
          %p
            = check_box_tag('reboot', true, @reboot)
            %label{for: "reboot"} Reboot suggested
        .box.show_left.show_right
          %p
            %strong
              = image_tag('info.png', title: 'Move specific binaries to the right select box by using the arrows', alt: 'Binaryinfo')
              Binaries:
          - if !@binarylist.blank?
            - available_bin = Array.new
            - @binarylist.each { |d| available_bin << "#{d.to_s}" }
            - selected_bin = Array.new
            - @binaries.each { |bin| selected_bin << "#{bin.to_s}" }
            #avail-bin{style: "float:left; width:44%; margin-left:5px;"}
              = select_tag 'available_binaries', options_for_select(available_bin), multiple: true, size: 6, style: 'width:100%;'
            #bin-options{style: "float:left; width:28px;"}
              %input#add{style: "width:28px;", type: "button", value: ">"}/
              %br/
              %input#add-all{style: "width:28px;", type: "button", value: ">>"}/
              %br/
              %input#remove-all{style: "width:28px;", type: "button", value: "<<"}/
              %br/
              %input#remove{style: "width:28px;", type: "button", value: "<"}/
              %br/
            #sele-bin{style: "width:44%; float:left;"}
              - if !selected_bin.blank?
                = select_tag 'selected_binaries', options_for_select(selected_bin), multiple: true, size: 6, style: 'width:100%;'
              - else
                = select_tag 'selected_binaries', "<option value=''></option>".html_safe, multiple: true, size: 6, style: 'width:100%;'
            %br{style: "clear:both;"}/
          - else
            %strong No binaries available!
        .box.ui-state-error.ui-widget-shadow.show_left.show_right{style: "padding-bottom:5px;"}
          %p
            %strong Block release?
            = check_box_tag('block', 'true', @block)
          %p
            %strong Reason:
            = text_field_tag('block_reason', @block_reason, style: 'width: 99%', disabled: true)
        %div{style: "margin-left:5px;"}
          = submit_tag 'Save Patchinfo'
        = hidden_field_tag "name", @name
- content_for :ready_function do
  patchinfoReady();

src/api/app/views/webui/patchinfo/edit_patchinfo.html.haml
- @pagetitle = "Patchinfo-Editor"
- patchinfo_bread_crumb 'Edit Patchinfo'
= render partial: 'form'

src/api/app/views/webui/patchinfo/new_patchinfo.html.haml
- @pagetitle = "Create Patchinfo"
- patchinfo_bread_crumb 'Create Patchinfo'
= render partial: 'form'

src/api/app/views/webui/patchinfo/show.html.haml
- @pagetitle = @package
- patchinfo_bread_crumb 'Patchinfo'
= render partial: 'webui/package/tabs'
.section
  .grid_8.alpha
    .box.show_left.show_right
      .box{style: "background-color:#DDDDDD; margin-top: 0"}
        %h2{style: "display: inline"}
          = @category
          update for #{truncate(@pkg_names.join(', '), length: 20)}
        - if User.current.can_modify_package?(@package)
          %ul.horizontal-list
            %li
              = link_to sprite_tag('package_edit'), { action: 'edit_patchinfo', project: @project, package: @package, spec_count: @spec_count }
              = link_to "Edit patchinfo", { action: 'edit_patchinfo', project: @project, package: @package, spec_count: @spec_count }, id: 'edit-patchinfo'
            %li
              = link_to(sprite_tag('package_delete'), { action: :delete_dialog, package: @package, project: @project }, remote: true)
              = link_to('Delete patchinfo', { action: :delete_dialog, package: @package, project: @project }, remote: true, id: 'delete-patchinfo')
      - if @block
        .box.ui-state-error.ui-widget-shadow{ style: "min-height:15px;" }
          %b This update is currently blocked:
          %br/
          - if @block_reason.present?
            = @block_reason
          - else
            No reason entered.
      %strong#summary= @summary
      %br/
      %label#info
      - if @packager
        This update was submitted from #{user_with_realname_and_icon(@packager)} and rated as
      - else
        This update is rated as
      %span{ style: "color: #{patchinfo_rating_color(@rating)}" }= @rating
    .box.show_left.show_right
      %b Description:
      %br/
      = description_wrapper(@description)
    .box.show_left.show_right
      %b Fixed bugs:
      - if @issues.present?
        %ul
          - @issues.each do |issue|
            - if issue[0] == "CVE"
              %li
                = link_to((issue[1]).to_s, issue[2]) + ": #{issue[3]}"
            - else
              %li
                = link_to("#{issue[0]}##{issue[1]}", issue[2]) + ": #{issue[3]}"
    .box.show_left.show_right
      %b Required actions:
      %br/
      %ul
        %li
          Relogin suggested:
          - if @relogin
            = image_tag "ok.png", id: "relogin_true"
          - else
            = image_tag "req-decline.png", id: "relogin_false"
        %li
          Reboot suggested:
          - if @reboot
            = image_tag "ok.png", id: "reboot_true"
          - else
            = image_tag "req-decline.png", id: "reboot_false"
        %li
          Package-manager restart:
          - if @zypp_restart_needed
            = image_tag "ok.png", id: "zypp_true"
          - else
            = image_tag "req-decline.png", id: "zypp_false"
    - unless @binaries.empty?
      .box.show_left.show_right
        %b Selected binaries:
        %br/
        %ul
          - @binaries.each do |bin|
            %li= bin